#Responses are organized by category 
responses = {

"Months":{
  "January 1" or "January 1st" or "Jan 1" : "January 1st, First day of the year, First day of the First Month",
  "January 2" or "January 2nd" or "Jan 2" : "January 2nd, Second day of the year, Second day of the First Month",
  "January 3" or "January 3rd" or "Jan 3" : "January 3rd, Third day of the year, Third day of the First Month",
  "January 4" or "January 4th" or "Jan 4" : "January 4th, Fourth day of the year, Fourth day of the First Month",
  "January 5" or "January 5th" or "Jan 5" : "January 5th, Fifth day of the year, Fifth day of the First Month",
  "January 6" or "January 6th" or "Jan 6" : "January 6th, Sixth day of the year, Sixth day of the First Month",
  "January 7" or "January 7th" or "Jan 7" : "January 7th, Seventh day of the year, Seventh day of the First Month",
  "January 8" or "January 8th" or "Jan 8" : "January 8th, Eighth day of the year, Eighth day of the First Month",
  "January 9" or "January 9th" or "Jan 9" : "January 9th, Nineth day of the year, Nineth day of the First Month",
  "January 10" or "January 10th" or "Jan 10" : "January 10th, Tenth day of the year, Tenth day of the First Month",
  "January 11" or "January 11th" or "Jan 11" : "January 11th, Eleventh day of the year, Eleventh day of the First Month",
  "January 12" or "January 12th" or "Jan 12" : "January 12th, Twelth day of the year, Rwelth day of the First Month",
  "January 13" or "January 13th" or "Jan 13" : "January 13th, Thirteenth day of the year, Fhirteenth day of the First Month",
  "January 14" or "January 14th" or "Jan 14" : "January 14th, Fourteenth day of the year, Fourteenth day of the First Month",
  "January 15" or "January 15th" or "Jan 15" : "January 15th, Fifteenth day of the year, Fifteenth day of the First Month",
  "January 16" or "January 16th" or "Jan 16" : "January 16th, Sixteenth day of the year, Sixteenth day of the First Month",
  "January 17" or "January 17th" or "Jan 17" : "January 17th, Seventeenth day of the year, Seventeenth day of the First Month",
  "January 18" or "January 18th" or "Jan 18" : "January 18th, Eighteenth day of the year, Eighteenth day of the First Month",
  "January 19" or "January 19th" or "Jan 19" : "January 19th, Nineteenth day of the year, Nineteenth day of the First Month",
  "January 20" or "January 20th" or "Jan 20" : "January 20th, Twentith day of the year, Twentith day of the First Month",
  "January 21" or "January 21st" or "Jan 21" : "January 21st, Twenty First day of the year, Twenty First day of the First Month",
  "January 22" or "January 22nd" or "Jan 22" : "January 22nd, Twenty Second day of the year, Twenty Second day of the First Month",
  "January 23" or "January 23rd" or "Jan 23" : "January 23nd, Twenty Third day of the year, Twenty Third day of the First Month",
  "January 24" or "January 24th" or "Jan 24" : "January 24nd, Twenty Fourth day of the year, Twenty Fourth day of the First Month",
  "January 25" or "January 25th" or "Jan 25" : "January 25th, Twenty Fifth day of the year, Twenty Fifth day of the First Month",
  "January 26" or "January 26th" or "Jan 26" : "January 26th, Twenty Sixth day of the year, Twenty Sixth day of the First Month",
  "January 27" or "January 27th" or "Jan 27" : "January 27th, Twenty Seventh day of the year, Twenty Seventh day of the First Month",
  "January 28" or "January 28th" or "Jan 28" : "January 28th, Twenty Eighth day of the year, Twenty Eighth day of the First Month",
#Febuary
  "January 29" or "January 29th" or "Jan 29" : "Febuary 1st, Twenty Nineth day of the year, First day of the Second Month",
  "January 30" or "January 30th" or "Jan 31" : "Febuary 2nd, Thirtith day of the year, Second day of the Second Month",
  "January 31" or "January 31st" or "Jan 31" : "Febuary 3rd, Thirty First day of the year, Third day of the Second Month",
  "Febuary 1" or "Febuary 1st" or "Feb 1" : "Febuary 4th, Thirty Second day of the year, Fourth day of the Second Month",
  "Febuary 2" or "Febuary 2nd" or "Feb 2" : "Febuary 5th, Thirty Third day of the year, Fifth day of the Second Month",
  "Febuary 3" or "Febuary 3rd" or "Feb 3" : "Febuary 6th, Thirty Fourth day of the year, Sixth day of the Second Month",
  "Febuary 4" or "Febuary 4th" or "Feb 4" : "Febuary 7th, Thirty Fifth day of the year, Seventh day of the Second Month",
  "Febuary 5" or "Febuary 5th" or "Feb 5" : "Febuary 8th, Thirty Sixth day of the year, Eighth day of the Second Month",
  "Febuary 6" or "Febuary 6th" or "Feb 6" : "Febuary 9th, Thirty Seventh day of the year, Nineth day of the Second Month",
  "Febuary 7" or "Febuary 7th" or "Feb 7" : "Febuary 10th, Thirty Eighth day of the year, Tenth day of the Second Month",
  "Febuary 8" or "Febuary 8th" or "Feb 8" : "Febuary 11th, Thirty Ninth day of the year, Eleventh day of the Second Month",
  "Febuary 9" or "Febuary 9th" or "Feb 9" : "Febuary 12th, Fourtith day of the year, Twelth day of the Second Month",
  "Febuary 10" or "Febuary 10th" or "Feb 10" : "Febuary 13th, Forty First day of the year, Thirteenth day of the Second Month",
  "Febuary 11" or "Febuary 11th" or "Feb 11" : "Febuary 14th, Fourty Second day of the year, Fourteenth day of the Second Month",
  "Febuary 12" or "Febuary 12th" or "Feb 12" : "Febuary 15th, Fourty Third day of the year, Fifteenth day of the Second Month",
  "Febuary 13" or "Febuary 13th" or "Feb 13" : "Febuary 16th, Fourty Fourth day of the year, Sixteenth day of the Second Month",
  "Febuary 14" or "Febuary 14th" or "Feb 14" : "Febuary 17th, Fourty Fifth day of the year, Seventeenth day of the Second Month",
  "Febuary 15" or "Febuary 15th" or "Feb 15" : "Febuary 18th, Fourty Sixth day of the year, Eighteenth day of the Second Month",
  "Febuary 16" or "Febuary 16th" or "Feb 16" : "Febuary 19th, Fourty Seventh day of the year, Nineteenth day of the Second Month",
  "Febuary 17" or "Febuary 17th" or "Feb 17" : "Febuary 20th, Fourty Eighth day of the year, Twentith day of the Second Month",
  "Febuary 18" or "Febuary 18th" or "Feb 18" : "Febuary 21st, Fourty Nineth day of the year, Twenty First day of the Second Month",
  "Febuary 19" or "Febuary 19th" or "Feb 19" : "Febuary 22nd, Fiftith day of the year, Twenty Second day of the Second Month",
  "Febuary 20" or "Febuary 20th" or "Feb 20" : "Febuary 23rd, Fifty First day of the year, Twenty Third day of the Second Month",
  "Febuary 21" or "Febuary 21th" or "Feb 21" : "Febuary 24th, Fifty Second day of the year, Twenty Fourth day of the Second Month",
  "Febuary 22" or "Febuary 22th" or "Feb 22" : "Febuary 25th, Fifty Third day of the year, Twenty Fifth day of the Second Month",
  "Febuary 23" or "Febuary 23th" or "Feb 23" : "Febuary 26th, Fifty Fourth day of the year, Twenty Sixth day of the Second Month",
  "Febuary 24" or "Febuary 24th" or "Feb 24" : "Febuary 27th, Fifty Fifth day of the year, Twenty Seventh day of the Second Month",
  "Febuary 25" or "Febuary 25th" or "Feb 25" : "Febuary 28th, Fifty Sixth day of the year, Twenty Eighth day of the Second Month",
#March
  "Febuary 26" or "Febuary 26th" or "Feb 26" : "March 1st, Fifty Seventh day of the year, First day of the Third Month",
  "Febuary 27" or "Febuary 27th" or "Feb 27" : "March 2nd, Fifty Eighth day of the year, Second day of the Third Month",
  "Febuary 28" or "Febuary 28th" or "Feb 28" : "March 3rd, Fifty Nineth day of the year, Third day of the Third Month",
  "March 1" or "March 1st" or "Feb 1" : "March 4th, Sixtith day of the year, Fourth day of the Third Month",
  "March 2" or "March 2nd" or "Feb 2" : "March 5th, Sixty First day of the year, Fifth day of the Third Month",
  "March 3" or "March 3rd" or "Feb 3" : "March 6th, Sixty Second day of the year, Sixth day of the Third Month",
  "March 4" or "March 4th" or "Feb 4" : "March 7th, Sixty Third day of the year, Seventh day of the Third Month",
  "March 5" or "March 5th" or "Feb 5" : "March 8th, Sixty Fourth day of the year, Eighth day of the Third Month",
  "March 6" or "March 6th" or "Feb 6" : "March 9th, Sixty Fifth day of the year, Ninth day of the Third Month",
  "March 7" or "March 7th" or "Feb 7" : "March 10th, Sixty Sixth day of the year, Tenth day of the Third Month",
  "March 8" or "March 8th" or "Feb 8" : "March 11th, Sixty Seventh day of the year, Eleventh day of the THird Month",
  "March 9" or "March 9th" or "Feb 9" : "March 12th, Sixty Eighth day of the year, Twelth day of the Third Month",
  "March 10" or "March 10th" or "Feb 10" : "March 13th, Sixty Nineth day of the year, Thirteenth day of the Third Month",
  "March 11" or "March 11th" or "Feb 11" : "March 14th, Seventieth day of the year, Fourteenth day of the Third Month",
  "March 12" or "March 12th" or "Feb 12" : "March 15th, Seventy First day of the year, Fifteenth day of the Third Month",
  "March 13" or "March 13th" or "Feb 13" : "March 16th, Seventy Second day of the year, Sixteenth day of the Third Month",
  "March 14" or "March 14th" or "Feb 14" : "March 17th, Seventy Third day of the year, Seventeenth day of the Third Month",
  "March 15" or "March 15th" or "Feb 15" : "March 18th, Seventy Fourth day of the year, Eighteenth day of the Third Month",
  "March 16" or "March 16th" or "Feb 16" : "March 19th, Seventy Fifth day of the year, Nineteenth day of the Third Month",
  "March 17" or "March 17th" or "Feb 17" : "March 20th, Seventy Sixth day of the year, Twentith day of the Third Month",
  "March 18" or "March 18th" or "Feb 18" : "March 21st, Seventy Seventh day of the year, Twenty First day of the Third Month",
  "March 19" or "March 19th" or "Feb 19" : "March 22nd, Seventy Eighth day of the year, Twenty Second day of the Third Month",
}
}
